egitim/Models/dersler.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace egitim.Models
{
    public class dersler
    {
        [Key]
        public int id { get; set; }
        [Display(Name ="Dersin Adı")]
        public string ders { get; set; }
        public ICollection<konular> konulars { get; set; }
        public ICollection<sinav> sinavs { get; set; }
        public ICollection<odev> odevs { get; set; }
        public ICollection<canli> canli { get; set; }
    }
}

egitim/Controllers/derslersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using egitim.Data;
using egitim.Models;

namespace egitim.Controllers
{
    public class derslersController : Controller
    {
        private readonly DataContext _context;

        public derslersController(DataContext context)
        {
            _context = context;
        }

        // GET: derslers
        public async Task<IActionResult> Index()
        {
            return View(await _context.derslers.ToListAsync());
        }

        // GET: derslers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dersler = await _context.derslers
                .FirstOrDefaultAsync(m => m.id == id);
            if (dersler == null)
            {
                return NotFound();
            }

            return View(dersler);
        }

        // GET: derslers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: derslers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,ders")] dersler dersler)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dersler);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dersler);
        }

        // GET: derslers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dersler = await _context.derslers.FindAsync(id);
            if (dersler == null)
            {
                return NotFound();
            }
            return View(dersler);
        }

        // POST: derslers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,ders")] dersler dersler)
        {
            if (id != dersler.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dersler);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!derslerExists(dersler.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dersler);
        }

        // GET: derslers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dersler = await _context.derslers
                .FirstOrDefaultAsync(m => m.id == id);
            if (dersler == null)
            {
                return NotFound();
            }

            return View(dersler);
        }

        // POST: derslers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dersler = await _context.derslers.FindAsync(id);
            _context.derslers.Remove(dersler);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool derslerExists(int id)
        {
            return _context.derslers.Any(e => e.id == id);
        }
    }
}

egitim/Views/derslers/Create.cshtml
@model egitim.Models.dersler

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layoutadmin.cshtml";
}

<h2>Create</h2>

<h4>dersler</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="derslers" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ders" class="control-label"></label>
                <input asp-for="ders" class="form-control" />
                <span asp-validation-for="ders" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

egitim/Views/derslers/Delete.cshtml
@model egitim.Models.dersler

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layoutadmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>dersler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ders)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ders)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

egitim/Views/derslers/Details.cshtml
@model egitim.Models.dersler

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layoutadmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>dersler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ders)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ders)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

egitim/Views/derslers/Edit.cshtml
@model egitim.Models.dersler

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layoutadmin.cshtml";
}

<h2>Edit</h2>

<h4>dersler</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="ders" class="control-label"></label>
                <input asp-for="ders" class="form-control" />
                <span asp-validation-for="ders" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

egitim/Views/derslers/Index.cshtml
@model IEnumerable<egitim.Models.dersler>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layoutadmin.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ders)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ders)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>